import { pawlyTokens } from '@/theme/pawlyTokens';

export const drawerTokens = {
  color: {
    page: pawlyTokens.color.page,
    heading: pawlyTokens.color.heading,
    body: pawlyTokens.color.body,
    action: pawlyTokens.color.action,
    actionStrong: pawlyTokens.color.link,
    onAction: '#ffffff',
    softPrimary: '#fdece8',
    overlay: 'rgba(26,28,26,0.4)',
    divider: 'rgba(219,193,185,0.3)',
    footer: '#f4f3f1',
    footerBorder: 'rgba(219,193,185,0.2)',
    disabled: '#8d817d',
    shadow: '#000000',
  },
  font: pawlyTokens.font,
  motion: {
    openDuration: 220,
    closeDuration: 180,
  },
  spacing: {
    xs: 4,
    md: 8,
    lg: 12,
    xl: 16,
  },
  state: {
    addOpacity: 0.6,
    pressedOpacity: 0.65,
  },
  shadow: {
    avatarWeb: pawlyTokens.shadow.avatar.web,
    avatarOffset: pawlyTokens.shadow.avatar.offset.height,
    avatarOpacity: pawlyTokens.shadow.avatar.opacity,
    avatarRadius: pawlyTokens.shadow.avatar.radius,
    avatarElevation: pawlyTokens.shadow.avatar.elevation,
    badgeWeb: pawlyTokens.shadow.badge.web,
    badgeOffset: pawlyTokens.shadow.badge.offset.height,
    badgeOpacity: pawlyTokens.shadow.badge.opacity,
    badgeRadius: pawlyTokens.shadow.badge.radius,
    badgeElevation: pawlyTokens.shadow.badge.elevation,
    drawerWeb:
      '0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1)',
    drawerOffsetX: 8,
    drawerOffsetY: 12,
    drawerOpacity: 0.1,
    drawerRadius: 12.5,
    drawerElevation: 12,
  },
  layout: {
    referenceWidth: 402,
    referenceHeight: 874,
    width: 320,
    minimumBackdropTarget: 32,
    cornerRadius: 24,
    safeTop: 54,
    headerHorizontalPadding: 16,
    headerBottomPadding: 8,
    bodyHorizontalPadding: 16,
    bodyVerticalPadding: 8,
    bodyGap: 8,
    menuWidth: 272,
    menuHorizontalInset: 48,
    menuItemHeight: 44.48,
    dividerHeight: 1,
    footerHorizontalPadding: 32,
    footerTopPadding: 25,
    footerBottomPadding: 24,
    footerContentHeight: 21,
    petLabelWidth: 72,
  },
  avatar: {
    borderWidth: 2,
    imagePadding: 2,
    userSize: pawlyTokens.component.userAvatar.largeSize,
    userRadius: pawlyTokens.component.userAvatar.largeRadius,
    userBadgeSize: pawlyTokens.component.userAvatar.largeBadgeSize,
    userBadgeOffset: pawlyTokens.component.userAvatar.largeBadgeOffset,
    userEditIconSize: pawlyTokens.component.userAvatar.largeEditIconSize,
    petSize: 64,
    petBadgeSize: 24,
    petBadgeOffset: -4,
    petEditIconSize: 8,
  },
  typography: {
    title: {
      fontSize: 24,
      lineHeight: 32,
    },
    body: {
      fontSize: 14,
      lineHeight: 21,
    },
    caption: {
      fontSize: 12,
      lineHeight: 18,
    },
    menuLabel: {
      fontSize: 16,
      lineHeight: 20.48,
      letterSpacing: 0.08,
    },
  },
} as const;
