export const pawlyTokens = {
  color: {
    page: '#faf9f6',
    heading: '#241c1a',
    body: '#55433d',
    caption: '#776964',
    link: '#9b543e',
    action: '#d97757',
    progressActive: '#99462a',
    progressInactive: '#e9e8e5',
    loaderTrack: '#e4e3df',
    onAction: '#faf9f6',
  },
  font: {
    quicksandRegular: 'Quicksand_400Regular',
    quicksandSemiBold: 'Quicksand_600SemiBold',
    jakartaRegular: 'PlusJakartaSans_400Regular',
    jakartaMedium: 'PlusJakartaSans_500Medium',
    jakartaSemiBold: 'PlusJakartaSans_600SemiBold',
    jakartaBold: 'PlusJakartaSans_700Bold',
  },
  interaction: {
    minimumTouchTarget: 44,
  },
  shadow: {
    avatar: {
      web:
        '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)',
      color: '#000000',
      offset: {
        width: 0,
        height: 8,
      },
      opacity: 0.1,
      radius: 7,
      elevation: 4,
    },
    badge: {
      web: '0 1px 1px rgba(0,0,0,0.05)',
      color: '#000000',
      offset: {
        width: 0,
        height: 1,
      },
      opacity: 0.05,
      radius: 1,
      elevation: 1,
    },
  },
  component: {
    footer: {
      gap: 12,
      horizontalPadding: 16,
      minimumBottomPadding: 20,
      topPadding: 20,
    },
    inputField: {
      borderRadius: 8,
      borderWidth: 1,
      gap: 8,
      horizontalPadding: 16,
      iconSize: 20,
      verticalPadding: 12,
    },
    userAvatar: {
      borderColor: '#ffffff',
      borderWidth: 2,
      imagePadding: 2,
      largeSize: 80,
      largeRadius: 16,
      largeBadgeSize: 32,
      largeBadgeOffset: -8,
      largeEditIconSize: 14,
      badgeColor: '#d97757',
    },
  },
  screen: {
    width: 402,
    splashHeight: 874,
    onboardingHeight: 858,
    safeTop: 54,
    headerHeight: 110,
    footerHeight: 156,
  },
} as const;
